#Descriptive Statistics 
honeyvar = read.csv("honeyvar.csv")
summary(honeyvar)

#Question 1 (Anova Analysis)
randomized_block_design = read.csv("Q1Project.csv")
randomized_block_design_aov = aov(ProdValue ~  State + Year, randomized_block_design)
(rbd_anova = anova(randomized_block_design_aov))
install.packages("agricolae")
library(agricolae)
(LSD.test(randomized_block_design_aov, "State", group = FALSE))

#Question 2 (Simple Regression)
honey = read.csv("honeysplit_0.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Alabama")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_1.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Arkansas")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_2.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Arizona")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_3.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="California")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_4.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Colorado")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_5.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Florida")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_6.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Georgia")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_7.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Hawaii")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_8.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Iowa")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_9.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Idaho")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_10.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Illinois")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_11.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Indiana")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_12.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Kansas")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_13.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Kentucky")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_14.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Louisiana")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_15.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Maine")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_16.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Michigan")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_17.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Minnesota")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_18.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Missouri")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_19.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Mississippi")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_20.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Montana")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_21.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="North Carolina")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_22.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="North Dakota")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_23.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Nebraska")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_24.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="New Jersey")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_25.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="New Mexico")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_26.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="New York")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_27.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Ohio")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_28.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Oregon")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_29.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Pennsylvania")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_30.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="South Dakota")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_31.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Tennessee")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_32.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Texas")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_33.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Utah")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_34.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Virginia")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_35.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Vermont")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_36.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Washington")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)


honey = read.csv("honeysplit_37.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Wisconsin")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_38.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="West Virginia")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)

honey = read.csv("honeysplit_39.csv")
honey_lm = lm(priceperlb ~ totalprod, data = honey)
summary(honey_lm) 
plot(honey$totalprod, honey$priceperlb, main="Wyoming")
abline(lm(priceperlb ~ totalprod, data=honey))
plot(honey_lm)



#Question 3 (Multiple Regression)
honey = read.csv("honeysplit.csv")
honey$state = relevel(honey$state, ref = "AL")
honey_lm = lm(priceperlb ~ totalprod + factor(state), data = honey)
summary(honey_lm)
plot(honey_lm)


